// 1. L'islam, vraie religon
const souratesIslamVrai = [
    "Unicité de la religion", 3, 3, 5, 30, 42, 86, 86, 6,
    "Le coran, révélation, vérité et guide",2,17,39,41,53,53,69,
    "Critique des Gens du Livre et des oppositions", 2,2,3,4,
    "Triomphe de l’islam sur les autres religions",   9, 24,48,61,61,
];
const versetsIslamVrai = [
    "", 19, 85, 3, 13, 30, 13, 14, 92,
    "",2,9,23,42,3,4,40,
    "", 146,159,99,46,
    "", 33, 55,28,8,9,
];
const ahadithsIslamVrai = [
  {
    sujet: "Le Coran comme guide",
    auteur: "صحيح البخاري",
    numero: 1452,
    texteArabe: " إنِّي تارِكٌ فيكم ثَقَلينِ أوَّلُهما كتابُ اللهِ .... ",
    texteFrancais:
      "“Le meilleur d’entre vous est celui qui apprend le Coran et l’enseigne.”",
    lien: "https://dorar.net/hadith/sharh/13180",
    autres: "أحمد (412)",
  },
  {
    sujet: "Le Coran comme guide",
    auteur: "صحيح أحمد ",
    numero: 16957,
    texteArabe:
      " لَيَبْلُغَنَّ هَذَا الأَمْرُ مَا بَلَغَ اللَّيْلُ وَالنَّهَارُ ... ",
    texteFrancais:
      "“Cette religion atteindra tout ce que couvrent la nuit et le jour.”",
    lien: "https://dorar.net/h/Bl2xt8xG",
    autres: "الطبراني (2/58) (1280)",
  },
  {
    sujet: "Le Coran comme guide",
    auteur: "صحيح مسلم ",
    numero: 867,
    texteArabe: " إِنَّ أَصْدَقَ الْحَدِيثِ كِتَابُ اللَّهِ ",
    texteFrancais: "“La parole la plus véridique est le Livre d’Allah.”",
    lien: "https://dorar.net/hadith/sharh/121864",
    autres: "ابن ماجه (45)، وأحمد (14984)",
  },
  {
    sujet: "Les gens du livre en enfer!",
    auteur: "صحيح مسلم",
    numero: 2408,
    texteArabe: " إنِّي تارِكٌ فيكم ثَقَلينِ أوَّلُهما كتابُ اللهِ .... ",
    texteFrancais:
      "“Je laisse parmi vous deux choses importantes :la première est le Livre d’Allah, dans lequel se trouvent la guidée et la lumière…”",
    lien: "https://dorar.net/hadith/sharh/65857",
    autres: "أحمد (19265)",
  },

  {
    sujet: "Les gens du livre en enfer!",
    auteur: "صحيح مسلم",
    numero: 153,
    texteArabe:
      " لا يَسمَعُ بي أحَدٌ مِن هذه الأُمَّةِ يَهوديٌّ ولا نَصرانيٌّ ... ",
    texteFrancais:
      " ... quiconque parmi cette communauté — juif ou chrétien — entend parler de moi puis meurt sans croire en ce avec quoi j’ai été envoyé sera parmi les gens du Feu.",
    lien: "https://dorar.net/hadith/sharh/24095",
    autres: "",
  },
  {
    sujet: "Les divisions des monothéismes...",
    auteur: "صحيح الترمذي",
    numero: 2641,
    texteArabe:
      " افترقتِ اليهودُ على إحدَى وسبعينَ فرقةً , وافترقتِ النصارَى على اثنتَينِ وسبعينَ فرقةً , وستفترقُ هذه الأمةُ على ثلاثٍ وسبعينَ فرقةً كلُّها في النارِ إلا واحدةً",
    texteFrancais:
      "“Les juifs se sont divisés en 71 groupes… et ma communauté se divisera en 73 groupes…” ",
    lien: "https://dorar.net/hadith/sharh/87648",
    autres: "الطبراني (14/53) (14646)، والحاكم (444)",
  },
];

// 2. Les noms et attributs d'Allah
const souratesIslamAttributsAllah = [
  "Nul égal à Allah",
  42,
  42,
  42,
  112,
  112,
  112,
  112,
  "Les plus beaux Noms d’Allah",
  7,
  17,
  20,
  "Versets qui regroupent plusieurs attributs",
  59,
  59,
  59,
  2,
  "Attributs de connaissance et de science",
  6,
  49,
  "Attributs de miséricorde",
  39,
  7,
  "Attributs de puissance et domination",
  57,
  67,
  "Transcendance et unicité",
  42,

  "Les 99 noms d'Allah الأسماء الحسنى",
  "1. الرحمن — Le Tout-Miséricordieux ",
  "2. الرحيم — Le Très-Miséricordieux",
  "3. الملك — Le Roi, le Souverain",
  "4. القدوس — Le Très-Saint",
  "5. السلام — La Paix",
  "6. المؤمن — Le Garant de la foi",
  "7. المهيمن — Le Préservateur",
  "8. العزيز — Le Tout-Puissant",
  "9. الجبار — Le Contraignant",
  "10. المتكبر — Le Majestueux",
  "11. الخالق — Le Créateur",
  "12. البارئ — Le Producteur",
  "13. المصور — Le Formateur",
  "14. الغفار — Le Grand Pardonneur",
  "15. القهار — Le Dominateur suprême",
  "16. الوهاب — Le Donateur",
  "17. الرزاق — Le Pourvoyeur",
  "18. الفتاح — L’Ouvreur",
  "19. العليم — L’Omniscient",
  "20. القابض — Celui qui retient",
  "21. الباسط — Celui qui étend",
  "22. الخافض — Celui qui abaisse",
  "23. الرافع — Celui qui élève",
  "24. المعز — Celui qui honore",
  "25. المذل — Celui qui humilie",
  "26. السميع — L’Audient",
  "27. البصير — Le Clairvoyant",
  "28. الحكم — Le Juge",
  "29. العدل — Le Juste",
  "30. اللطيف — Le Subtil",
  "31. الخبير — Le Parfaitement Informé",
  "32. الحليم — Le Très Doux",
  "33. العظيم — L’Immense",
  "34. الغفور — Le Pardonneur",
  "35. الشكور — Le Très Reconnaissant",
  "36. العلي — Le Très Haut",
  "37. الكبير — Le Très Grand",
  "38. الحفيظ — Le Préservateur",
  "39. المقيت — Le Pourvoyeur",
  "40. الحسيب — Le Suffisant",
  "41. الجليل — Le Majestueux",
  "42. الكريم — Le Noble",
  "43. الرقيب — Le Vigilant",
  "44. المجيب — Celui qui exauce",
  "45. الواسع — L’Immense",
  "46. الحكيم — Le Sage",
  "47. الودود — Le Plein d’amour",
  "48. المجيد — Le Glorieux",
  "49. الباعث — Celui qui ressuscite",
  "50. الشهيد — Le Témoin",
  "51. الحق — La Vérité",
  "52. الوكيل — Le Garant",
  "53. القوي — Le Fort",
  "54. المتين — Le Très Fort",
  "55. الولي — Le Protecteur",
  "56. الحميد — Le Digne de louange",
  "57. المحصي — Celui qui recense",
  "58. المبدئ — Le Commenceur",
  "59. المعيد — Celui qui répète",
  "60. المحيي — Le Donneur de vie",
  "61. المميت — Celui qui fait mourir",
  "62. الحي — Le Vivant",
  "63. القيوم — L’Auto-subsistant",
  "64. الواجد — Le Trouveur",
  "65. الماجد — Le Noble",
  "66. الواحد — L’Unique",
  "67. الصمد — Le Parfait, le Seul vers qui on se tourne",
  "68. القادر — Le Capable",
  "69. المقتدر — Le Tout-Puissant",
  "70. المقدم — Celui qui avance",
  "71. المؤخر — Celui qui retarde",
  "72. الأول — Le Premier",
  "73. الآخر — Le Dernier",
  "74. الظاهر — L’Apparent",
  "75. الباطن — Le Caché",
  "76. الوالي — Le Gouverneur",
  "77. المتعالي — Le Très Élevé",
  "78. البر — Le Bienveillant",
  "79. التواب — Celui qui accepte le repentir",
  "80. المنتقم — Le Vengeur",
  "81. العفو — Celui qui efface les fautes",
  "82. الرؤوف — Le Compatissant",
  "83. مالك الملك — Le Maître de la royauté",
  "84. ذو الجلال والإكرام — Le Détenteur de majesté et de générosité",
  "85. المقسط — Le Juste équitable",
  "86. الجامع — Le Rassembleur",
  "87. الغني — Le Riche",
  "88. المغني — Celui qui enrichit",
  "89. المانع — Celui qui empêche",
  "90. الضار — Celui qui cause le mal (par sagesse)",
  "91. النافع — Celui qui apporte le bien",
  "92. النور — La Lumière",
  "93. الهادي — Le Guide",
  "94. البديع — Le Créateur sans modèle",
  "95. الباقي — L’Éternel",
  "96. الوارث — L’Héritier",
  "97. الرشيد — Le Bien-guidé",
  "98. الصبور — Le Très Patient",
  "99. الله — Allah (le Nom suprême)",
];
const versetsIslamAttributsAllah = [
  "",
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  "",
  180,
  110,
  8,
  "",
  22,
  23,
  24,
  255,
  "",
  59,
  16,
  "",
  53,
  156,
  "",
  1,
  1,
  "",
  11,
  
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];
const ahadithsIslamAttributsAllah = [
  {
    sujet: "Allah a 99 noms",
    auteur: "صحيح البخاري",
    numero: 6410,
    texteArabe:
      " لَّهِ تِسعةٌ وتِسعونَ اسمًا -مِائةٌ إلَّا واحِدًا- لا يَحفَظُها أحَدٌ إلَّا دَخَلَ الجَنَّةَ ",
    texteFrancais:
      "“Allah possède quatre-vingt-dix-neuf noms — cent moins un — quiconque les mémorise entrera au Paradis.”",
    lien: "https://dorar.net/hadith/sharh/132010",
    autres: "مسلم (2677)",
    },
    
];

// 3. Allah omnipotent / omnscient
const souratesIslamAllahOmni = [
    "1) La Science absolue d’Allah — العلم (Al-‘Ilm) ", 6, 6, 11, 13, 22, 33,
    "2) Sagesse et justice — الحكمة والعدل (Al-Ḥikma / Al-‘Adl) ", 3, 7, 22, 22, 22, 2,
    "3) La Puissance absolue — القدرة (Al-Qudra) ", 16, 36, 22, 40, 42, 32,
    "4) Volonté et gestion divine — الإرادة والتدبير (Al-Irāda / At-Tadbīr) ", 35, 32, 22,
    "5) Révélation et guidance — الوحي والبيان (Al-Waḥy) ", 6, 9, 11, 11, 42,
    "6)  Souveraineté et domination — الربوبية والسيادة (Ar-Rubūbiyya / Al-Mulk)", 6, 22, 35,
    "7) L’invisible et limites humaines — الغيب والحدود (Al-Ghayb)  ",17,11,6,
];
const versetsIslamAllahOmni = [
    "", 18, 103, 5, 9, 70, 54,
    "", 140, 5, 38, 39, 40, 181,
    "", 40, 82, 6, 68, 9, 5,
    "", 2, 5, 70,
    "", 115, 6, 2, 3, 17,
    "", 18, 6, 2,
    "",85,5,103,
];
let ahadithsIslamAllahOmni = [
  {
    auteur: "El Boukhari صحيح البخاري",
    numero: 4584,
    texte:
      "أَطِيعُوا اللَّهَ وَأَطِيعُوا الرَّسُولَ وَأُولِي الْأَمْرِ مِنْكُمْ",
    lien: "https://dorar.net/hadith/sharh/65277",
  },
  // https://dorar.net/hadith/sharh/24773
];


// 4. Allah le miséricordieux
const souratesIslam= [];
const versetsIslam = [];
const ahadithsIslam = [
  // https://dorar.net/hadith/sharh/85969 “Allah est plus miséricordieux envers Ses serviteurs que cette mère envers son enfant.”
  // https://dorar.net/hadith/sharh/16719  “Ô Mes serviteurs, Je Me suis interdit l’injustice et Je l’ai interdite entre vous, ne soyez donc pas injustes.”
];

